/*
 *   Copyright (C) 2017  Gyorgy Stercz
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/** \file gpiosetup.h
  * \brief  GPIO pin definitions and initialization.
  *
  * \author Gyorgy Stercz
  */

#ifndef GPIOSETUP_H_INCLUDED
#define GPIOSETUP_H_INCLUDED

#include <hal.h>

/** \brief Structure of GPIO pin.
  *
  */
struct GPIO_Pin{
    ioportid_t port;
    uint8_t pin;
    iomode_t mode;
};

/** \brief Pin table definitions of display on the stm32f746 discovery board.
  *
  * \{
  */

#define LCD_B0 {GPIOE, 4, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_B1 {GPIOJ, 13, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_B2 {GPIOJ, 14, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_B3 {GPIOJ, 15, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_B4 {GPIOG, 12, (PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_B5 {GPIOK, 4, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_B6 {GPIOK, 5, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_B7 {GPIOB, 6, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}

#define LCD_G0 {GPIOJ, 7, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_G1 {GPIOJ, 8, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_G2 {GPIOJ, 9, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_G3 {GPIOJ, 10, (PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_G4 {GPIOJ, 11, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_G5 {GPIOK, 0, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_G6 {GPIOK, 1, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_G7 {GPIOK, 2,  (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}

#define LCD_R0 {GPIOI, 15, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_R1 {GPIOJ, 0, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_R2 {GPIOJ, 1, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_R3 {GPIOJ, 2, (PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_R4 {GPIOJ, 3, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_R5 {GPIOJ, 4, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_R6 {GPIOJ, 5, (PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_R7 {GPIOJ, 6, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}

#define LCD_HSYNC {GPIOI, 10, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_VSYNC {GPIOI, 9, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_CLK {GPIOI, 14, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}
#define LCD_DE {GPIOK, 7, (PAL_MODE_ALTERNATE(14) | PAL_STM32_OSPEED_HIGHEST)}

#define LCD_BL_CTRL {GPIOK, 3, PAL_MODE_OUTPUT_PUSHPULL}
#define LCD_DISP_ON {GPIOI, 12, PAL_MODE_OUTPUT_PUSHPULL}
#define LCD_INT {GPIOI, 13, PAL_MODE_INPUT}

#define LCD_PIN_TABLE   {LCD_R0, LCD_R1, LCD_R2, LCD_R3, LCD_R4, LCD_R5, LCD_R6, LCD_R7, \
                         LCD_G0, LCD_G1, LCD_G2, LCD_G3, LCD_G4, LCD_G5, LCD_G6, LCD_G7, \
                         LCD_B0, LCD_B1, LCD_B2, LCD_B3, LCD_B4, LCD_B5, LCD_B6, LCD_B7, \
                         LCD_VSYNC, LCD_HSYNC, LCD_CLK, LCD_DE, \
                         LCD_BL_CTRL, \
                         LCD_DISP_ON, \
                         LCD_INT \
                         }
#define LCD_PIN_NUM 31
/** \} */


/** \brief Pin table definitions of sdram on the stm32f746 discovery board.
  *
  * \{
  */
#define FMC_A0 {GPIOF, 0, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_A1 {GPIOF, 1, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_A2 {GPIOF, 2, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_A3 {GPIOF, 3, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_A4 {GPIOF, 4, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_A5 {GPIOF, 5, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_A6 {GPIOF, 12, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_A7 {GPIOF, 13, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_A8 {GPIOF, 14, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_A9 {GPIOF, 15, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_A10 {GPIOG, 0, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_A11 {GPIOG, 1, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}

#define FMC_BA0 {GPIOG, 4, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_BA1 {GPIOG, 5, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}

#define FMC_SDNWE {GPIOH, 5, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_SDNCAS {GPIOG, 15, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_SDNRAS {GPIOF, 11, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_SDNE0 {GPIOH, 3, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_SDNCKE0 {GPIOC, 3, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_SDNCLK {GPIOG, 8, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}

#define FMC_NBL0 {GPIOE, 0, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_NBL1 {GPIOA, 0, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}

#define FMC_D0 {GPIOD, 14, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_D1 {GPIOD, 15, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_D2 {GPIOD, 0, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_D3 {GPIOD, 1, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_D4 {GPIOE, 7, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_D5 {GPIOE, 8, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_D6 {GPIOE, 9, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_D7 {GPIOE, 10, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_D8 {GPIOE, 11, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_D9 {GPIOE, 12, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_D10 {GPIOE, 13, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_D11 {GPIOE, 14, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_D12 {GPIOE, 15, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_D13 {GPIOD, 8, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_D14 {GPIOD, 9, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}
#define FMC_D15 {GPIOD, 10, (PAL_MODE_ALTERNATE(12) | PAL_STM32_OSPEED_HIGHEST)}

#define SDRAM_PIN_TABLE {FMC_A0, FMC_A1, FMC_A2, FMC_A3, FMC_A4, FMC_A5, FMC_A6, FMC_A7, FMC_A8, FMC_A9, FMC_A10, FMC_A11, \
                         FMC_BA0, FMC_BA1, FMC_SDNWE, FMC_SDNCAS, FMC_SDNRAS, FMC_SDNE0, FMC_SDNCKE0, FMC_SDNCLK, FMC_NBL0, FMC_NBL1, \
                         FMC_D0, FMC_D1, FMC_D2, FMC_D3, FMC_D4, FMC_D5, FMC_D6, FMC_D7, \
                         FMC_D8, FMC_D9, FMC_D10, FMC_D11, FMC_D12, FMC_D13, FMC_D14, FMC_D15}

#define SDRAM_PIN_NUM 38
/**\} */

/** \brief I2C bus pin definitions of touch sensor on the stm32f746 discovery board.
  *
  * \{
  */
#define TOUCH_SCL {GPIOH, 7, (PAL_MODE_ALTERNATE(4) | PAL_STM32_OTYPE_OPENDRAIN)}
#define TOUCH_SDA {GPIOH, 7, (PAL_MODE_ALTERNATE(4) | PAL_STM32_OTYPE_OPENDRAIN)}
/**\} */

/** \brief I2C bus pin definitions of temperature sensors.
  *
  * \{
  */
#define TSENS_SCL {GPIOB, 8, (PAL_MODE_ALTERNATE(4) | PAL_STM32_OTYPE_OPENDRAIN)}
#define TSENS_SDA {GPIOB, 9, (PAL_MODE_ALTERNATE(4) | PAL_STM32_OTYPE_OPENDRAIN)}
/**\} */

/** \brief Pin definitions of SDC
  *
  * \{
  */
#define SDC_D0 {GPIOC, 8, PAL_MODE_ALTERNATE(12)}
#define SDC_D1 {GPIOC, 9, PAL_MODE_ALTERNATE(12)}
#define SDC_D2 {GPIOC, 10, PAL_MODE_ALTERNATE(12)}
#define SDC_D3 {GPIOC, 11, PAL_MODE_ALTERNATE(12)}
#define SDC_CMD_PIN {GPIOD, 2, PAL_MODE_ALTERNATE(12)}
#define SDC_CK {GPIOC, 12, PAL_MODE_ALTERNATE(12)}
#define SDC_DETECT {GPIOC, 13, PAL_MODE_INPUT_PULLUP}

#define SDC_PIN_TABLE {SDC_D0, SDC_D1, SDC_D2, SDC_D3, SDC_CMD_PIN, SDC_CK, SDC_DETECT}
#define SDC_PIN_NUM 7
/**\} */

/** \brief PWM pin definitions.
  *
  * \{
  */
#define PWM_CH0 {GPIOB, 4, PAL_MODE_ALTERNATE(2)}
#define PWM_CH1 {GPIOA, 8, PAL_MODE_ALTERNATE(1)}
#define PWM_CH2 {GPIOI, 0, PAL_MODE_ALTERNATE(2)}
/**\} */

/** \brief Channels external interrupt (relay) pin definitions.
  *
  * \{
  */
#define INT_CH0 {GPIOI, 2, PAL_MODE_INPUT}
#define INT_CH1 {GPIOA, 15, PAL_MODE_INPUT}
#define INT_CH2 {GPIOB, 14, PAL_MODE_INPUT}
/**\} */


/** \brief Printer serial port pin definitions.
  *
  * \{
  */
#define PRINTER_TX {GPIOC, 6, PAL_MODE_ALTERNATE(8)}
#define PRINTER_RX {GPIOC, 7, PAL_MODE_ALTERNATE(8)}
/**\} */

/** \brief Configures GPIO pins
  */
void gpioInit(void);

#endif // GPIOSETUP_H_INCLUDED
